/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.chromium.chrome;

public final class R {
    public static final class attr {
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int action_mode_share_drawable=0x7f010000;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int action_mode_web_search_drawable=0x7f010001;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int select_dialog_multichoice=0x7f010002;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int select_dialog_singlechoice=0x7f010003;
    }
    public static final class bool {
        /**  TabStrip text 
         */
        public static int tab_title_fake_bold_text=0x7f0b0000;
    }
    public static final class color {
        public static int button_focused=0x7f06002b;
        /**  Button Colors 
         */
        public static int button_pressed=0x7f06002a;
        public static int color_picker_border_color=0x7f060000;
        /**  Data Reduction Colors 
         */
        public static int data_reduction_percent_color=0x7f060029;
        /**  Disabled Colors 
         */
        public static int disable_pref_activity=0x7f06002c;
        public static int find_result_bar_active_border_color=0x7f060014;
        public static int find_result_bar_active_color=0x7f060013;
        public static int find_result_bar_background_border_color=0x7f060010;
        /**  Find in Page colors 
         */
        public static int find_result_bar_background_color=0x7f06000f;
        public static int find_result_bar_no_results_background_color=0x7f060015;
        public static int find_result_bar_result_border_color=0x7f060012;
        public static int find_result_bar_result_color=0x7f060011;
        /**  First Run Experience Colors 
         */
        public static int fre_background_color=0x7f060020;
        public static int fre_light_text_color_tablet=0x7f060026;
        public static int fre_negative_button_color=0x7f060024;
        public static int fre_negative_button_color_tablet=0x7f060027;
        public static int fre_positive_button_color=0x7f060023;
        public static int fre_text_color=0x7f060022;
        /**  First Run colors for tablet 
         */
        public static int fre_text_color_tablet=0x7f060025;
        public static int fre_thin_line_color=0x7f060021;
        public static int infobar_info_background_separator=0x7f060017;
        /**  Colors were copied from browser/views/infobars/infobars.cc 
         */
        public static int infobar_text=0x7f060016;
        public static int infobar_warning_background_separator=0x7f060018;
        /**  App Launch Colors 
         */
        public static int light_background_color=0x7f060028;
        /**  LocationBar colors 
         */
        public static int locationbar_default_text=0x7f060001;
        public static int locationbar_domain_and_registry=0x7f060008;
        public static int locationbar_scheme_to_domain=0x7f060007;
        public static int locationbar_start_scheme_default=0x7f060002;
        public static int locationbar_start_scheme_ev_secure=0x7f060005;
        public static int locationbar_start_scheme_secure=0x7f060006;
        public static int locationbar_start_scheme_security_error=0x7f060004;
        public static int locationbar_start_scheme_security_warning=0x7f060003;
        public static int locationbar_trailing_url=0x7f060009;
        /**  New Tab Page Colors 
         */
        public static int new_tab_page_bg=0x7f06002d;
        /**  The color of the divider between omnibox suggestions. 
         */
        public static int omnibox_divider=0x7f06000a;
        public static int tab_back=0x7f06001e;
        public static int tab_back_incognito=0x7f06001f;
        /**  Tab Switcher Colors 
         */
        public static int tab_switcher_background=0x7f060019;
        public static int tab_title_bar_shadow=0x7f06001c;
        public static int tab_title_bar_shadow_incognito=0x7f06001d;
        public static int tab_title_bar_text=0x7f06001a;
        public static int tab_title_bar_text_incognito=0x7f06001b;
        /**  Toolbar color 
         */
        public static int toolbar_color=0x7f06000e;
        public static int toolbar_incognito_tab_count_color=0x7f06000c;
        public static int toolbar_switcher_tab_count_color=0x7f06000d;
        /**  Tab Count Colors 
         */
        public static int toolbar_tab_count_color=0x7f06000b;
        /**  WebappActivity colors 
         */
        public static int webapp_url_bar_scheme=0x7f06002e;
    }
    public static final class dimen {
        /**  Certificate Viewer Dimensions 
         */
        public static int certificate_viewer_padding=0x7f070009;
        /** 
         14.5 = Seekbar thumb width - border width, but it depends on the width
	     of the seek bar icon.
    
         */
        public static int color_picker_gradient_margin=0x7f070000;
        /**  Left/right padding for infobar button text. 
         */
        public static int infobar_button_horizontal_padding=0x7f070005;
        /**  Text size of text inside InfoBar buttons. 
         */
        public static int infobar_button_text_size=0x7f070002;
        /**  Dimension (height or width) of the InfoBar icon. 
         */
        public static int infobar_icon_size=0x7f070007;
        /**  Margin between items in an InfoBar. 
         */
        public static int infobar_margin=0x7f070004;
        /**  Minimum dimension (height or width) of the upper row of an InfoBar. 
         */
        public static int infobar_min_size=0x7f070003;
        /**  Infobar dimensions 
 Text size of the InfoBar message. 
         */
        public static int infobar_text_size=0x7f070001;
        /**  Minimum height for a touch target. 
         */
        public static int infobar_touch_target_height=0x7f070006;
        /**  Link Preview dimensions 
         */
        public static int link_preview_overlay_radius=0x7f070008;
    }
    public static final class drawable {
        public static int autofill_popup_background=0x7f020000;
        public static int autofill_popup_background_down=0x7f020001;
        public static int autofill_popup_background_up=0x7f020002;
        public static int bubble=0x7f020003;
        public static int bubble_arrow_up=0x7f020004;
        public static int color_picker_advanced_select_handle=0x7f020005;
        public static int color_picker_border=0x7f020006;
        public static int controlled_setting_mandatory_large=0x7f020007;
        public static int globe_favicon=0x7f020008;
        public static int ic_menu_search_holo_light=0x7f020009;
        public static int ic_menu_share_holo_light=0x7f02000a;
        public static int infobar_autofill=0x7f02000b;
        public static int infobar_autologin=0x7f02000c;
        public static int infobar_blocked_popups=0x7f02000d;
        public static int infobar_button_normal_floating=0x7f02000e;
        public static int infobar_button_normal_floating_enabled=0x7f02000f;
        public static int infobar_button_normal_floating_pressed=0x7f020010;
        public static int infobar_button_normal_full_left=0x7f020011;
        public static int infobar_button_normal_full_left_enabled=0x7f020012;
        public static int infobar_button_normal_full_left_pressed=0x7f020013;
        public static int infobar_button_normal_full_right=0x7f020014;
        public static int infobar_button_normal_full_right_enabled=0x7f020015;
        public static int infobar_button_normal_full_right_pressed=0x7f020016;
        public static int infobar_button_text=0x7f020017;
        public static int infobar_button_warning_floating=0x7f020018;
        public static int infobar_button_warning_floating_enabled=0x7f020019;
        public static int infobar_button_warning_floating_pressed=0x7f02001a;
        public static int infobar_button_warning_full_left=0x7f02001b;
        public static int infobar_button_warning_full_left_enabled=0x7f02001c;
        public static int infobar_button_warning_full_left_pressed=0x7f02001d;
        public static int infobar_button_warning_full_right=0x7f02001e;
        public static int infobar_button_warning_full_right_enabled=0x7f02001f;
        public static int infobar_button_warning_full_right_pressed=0x7f020020;
        public static int infobar_camera=0x7f020021;
        public static int infobar_close_bg=0x7f020022;
        public static int infobar_close_button_focused=0x7f020023;
        public static int infobar_close_button_pressed=0x7f020024;
        public static int infobar_cookie=0x7f020025;
        public static int infobar_desktop_notifications=0x7f020026;
        public static int infobar_didyoumean=0x7f020027;
        public static int infobar_dismiss=0x7f020028;
        public static int infobar_geolocation=0x7f020029;
        public static int infobar_incomplete=0x7f02002a;
        public static int infobar_info_background=0x7f02002b;
        public static int infobar_microphone=0x7f02002c;
        public static int infobar_multiple_downloads=0x7f02002d;
        public static int infobar_plugin=0x7f02002e;
        public static int infobar_plugin_crashed=0x7f02002f;
        public static int infobar_restore=0x7f020030;
        public static int infobar_savepassword=0x7f020031;
        public static int infobar_theme=0x7f020032;
        public static int infobar_translate=0x7f020033;
        public static int infobar_update_uma=0x7f020034;
        public static int infobar_warning=0x7f020035;
        public static int infobar_warning_background=0x7f020036;
        public static int missing=0x7f020037;
        /**  Notification Colors 
         */
        public static int notification_icon_bg=0x7f02003f;
        public static int ondemand_overlay=0x7f020038;
        public static int pageinfo_bad=0x7f020039;
        public static int pageinfo_good=0x7f02003a;
        public static int pageinfo_info=0x7f02003b;
        public static int pageinfo_warning_major=0x7f02003c;
        public static int pageinfo_warning_minor=0x7f02003d;
        public static int warning=0x7f02003e;
    }
    public static final class floats {
        public static int top_controls_hide_threshold=0x7f0c0001;
        /**  Full Screen Constants 
 These constants were chosen empirically for their visually pleasant behavior.
         Contact tedchoc@chromium.org or dtrainor@chromium.org for questions about
         changing these values. 
         */
        public static int top_controls_show_threshold=0x7f0c0000;
    }
    public static final class id {
        public static int ampm=0x7f090020;
        public static int arrow_image=0x7f090027;
        public static int autofill_label=0x7f090008;
        public static int autofill_menu_text=0x7f090007;
        /**  AutofillPopup constants 
         */
        public static int autofill_popup_window=0x7f090000;
        public static int autofill_sublabel=0x7f090009;
        public static int button_primary=0x7f090003;
        public static int button_secondary=0x7f090004;
        public static int color_picker_advanced=0x7f09000e;
        public static int color_picker_simple=0x7f090010;
        public static int color_picker_simple_border=0x7f09000f;
        public static int date_picker=0x7f090016;
        public static int gradient=0x7f09000c;
        public static int gradient_border=0x7f09000b;
        public static int hour=0x7f09001a;
        public static int icon_view=0x7f090025;
        public static int infobar_close_button=0x7f090002;
        public static int infobar_extra_check=0x7f090005;
        /**  InfoBar constants 
         */
        public static int infobar_message=0x7f090001;
        public static int js_modal_dialog_prompt=0x7f090018;
        public static int main_text=0x7f090028;
        public static int milli=0x7f09001f;
        public static int minute=0x7f09001b;
        public static int more_colors_button=0x7f090012;
        public static int more_colors_button_border=0x7f090011;
        public static int pickers=0x7f090021;
        public static int position_in_year=0x7f090022;
        /**  Notifications 
         */
        public static int remote_notification=0x7f090006;
        public static int second=0x7f09001d;
        public static int second_colon=0x7f09001c;
        public static int second_dot=0x7f09001e;
        public static int seek_bar=0x7f09000d;
        public static int selected_color_view=0x7f090015;
        public static int selected_color_view_border=0x7f090014;
        public static int sub_text=0x7f090029;
        public static int suppress_js_modal_dialogs=0x7f090019;
        public static int text=0x7f09000a;
        public static int text_wrapper=0x7f090026;
        public static int time_picker=0x7f090017;
        public static int title=0x7f090013;
        public static int top_view=0x7f090024;
        public static int website_settings_description=0x7f09002c;
        public static int website_settings_headline=0x7f09002b;
        public static int website_settings_icon=0x7f09002a;
        public static int year=0x7f090023;
    }
    public static final class integer {
        /**  The number of approximation thumbnails that the approximation cache can hold. 
         */
        public static int default_approximation_thumbnail_cache_size=0x7f0a0001;
        /**  The maximum size of the compression queue in the thumbnail cache. 
         */
        public static int default_compression_queue_size=0x7f0a0003;
        /**  The number of thumbnails that the thumbnail cache can hold. 
         */
        public static int default_thumbnail_cache_size=0x7f0a0000;
        /**  The maximum size of the write queue in the thumbnail cache. 
         */
        public static int default_write_queue_size=0x7f0a0002;
        /**  FRE and App Start 
 Long duration in ms for animation and callbacks 
         */
        public static int fre_long_duration_ms=0x7f0a0006;
        /**  TabSwitcher - Maximum amount to tilt tabs in over scroll in degrees. 
         */
        public static int over_scroll_angle=0x7f0a0005;
        /**  The maximum indent depth of folders when selecting bookmarks. 
         */
        public static int select_bookmark_folder_max_depth_indent=0x7f0a0004;
    }
    public static final class layout {
        public static int autofill_text=0x7f040000;
        public static int color_picker_advanced_component=0x7f040001;
        public static int color_picker_dialog_content=0x7f040002;
        public static int color_picker_dialog_title=0x7f040003;
        public static int date_time_picker_dialog=0x7f040004;
        public static int dimens=0x7f040005;
        public static int infobar_button=0x7f040006;
        public static int infobar_text=0x7f040007;
        public static int js_modal_dialog=0x7f040008;
        public static int multi_field_time_picker_dialog=0x7f040009;
        public static int two_field_date_picker=0x7f04000a;
        public static int validation_message_bubble=0x7f04000b;
        public static int website_settings=0x7f04000c;
    }
    public static final class mipmap {
        public static int app_icon=0x7f030000;
        public static int bookmark_widget_bg=0x7f030001;
        public static int bookmark_widget_bg_highlights=0x7f030002;
    }
    public static final class string {
        public static int accessibility_content_view=0x7f05000b;
        public static int accessibility_date_picker_month=0x7f05001a;
        public static int accessibility_date_picker_week=0x7f05001b;
        public static int accessibility_date_picker_year=0x7f05001c;
        public static int accessibility_datetime_picker_date=0x7f050018;
        public static int accessibility_datetime_picker_time=0x7f050019;
        public static int accessibility_js_modal_dialog_prompt=0x7f05002e;
        public static int accessibility_time_picker_ampm=0x7f050021;
        public static int accessibility_time_picker_hour=0x7f05001d;
        public static int accessibility_time_picker_milli=0x7f050020;
        public static int accessibility_time_picker_minute=0x7f05001e;
        public static int accessibility_time_picker_second=0x7f05001f;
        public static int actionbar_share=0x7f050009;
        public static int actionbar_web_search=0x7f05000a;
        public static int certtitle=0x7f05002f;
        public static int color_picker_button_cancel=0x7f050007;
        public static int color_picker_button_more=0x7f050002;
        public static int color_picker_button_set=0x7f050006;
        public static int color_picker_dialog_title=0x7f050008;
        public static int color_picker_hue=0x7f050003;
        public static int color_picker_saturation=0x7f050004;
        public static int color_picker_value=0x7f050005;
        public static int date_picker_dialog_clear=0x7f05000d;
        public static int date_picker_dialog_set=0x7f05000c;
        public static int date_picker_dialog_title=0x7f05000e;
        public static int date_time_picker_dialog_title=0x7f05000f;
        public static int dont_reload_this_page=0x7f05002a;
        public static int firstrun_signed_in_description=0x7f05003d;
        public static int firstrun_signed_in_title=0x7f05003c;
        public static int infobar_close=0x7f05003b;
        public static int js_modal_dialog_cancel=0x7f05002c;
        public static int js_modal_dialog_confirm=0x7f05002b;
        public static int leave_this_page=0x7f050027;
        public static int low_memory_error=0x7f050000;
        public static int media_player_error_button=0x7f050025;
        public static int media_player_error_text_invalid_progressive_playback=0x7f050023;
        public static int media_player_error_text_unknown=0x7f050024;
        public static int media_player_error_title=0x7f050022;
        public static int media_player_loading_video=0x7f050026;
        public static int month_picker_dialog_title=0x7f050016;
        public static int opening_file_error=0x7f050001;
        public static int policy_dialog_cancel=0x7f050038;
        public static int policy_dialog_message=0x7f050036;
        public static int policy_dialog_proceed=0x7f050037;
        public static int policy_dialog_title=0x7f050035;
        public static int reload_this_page=0x7f050029;
        public static int sad_tab_help_link=0x7f050041;
        public static int sad_tab_help_message=0x7f050040;
        public static int sad_tab_message=0x7f05003f;
        public static int sad_tab_reload_label=0x7f050042;
        public static int sad_tab_title=0x7f05003e;
        public static int stay_on_this_page=0x7f050028;
        public static int suppress_js_modal_dialogs=0x7f05002d;
        public static int sync_error_connection=0x7f050032;
        public static int sync_error_domain=0x7f050033;
        public static int sync_error_ga=0x7f050031;
        public static int sync_error_generic=0x7f050030;
        public static int sync_error_service_unavailable=0x7f050034;
        public static int time_picker_dialog_am=0x7f050011;
        public static int time_picker_dialog_hour_minute_separator=0x7f050013;
        public static int time_picker_dialog_minute_second_separator=0x7f050014;
        public static int time_picker_dialog_pm=0x7f050012;
        public static int time_picker_dialog_second_subsecond_separator=0x7f050015;
        public static int time_picker_dialog_title=0x7f050010;
        public static int week_picker_dialog_title=0x7f050017;
        public static int wiping_profile_data_message=0x7f05003a;
        public static int wiping_profile_data_title=0x7f050039;
    }
    public static final class style {
        public static int AutofillPopupWindow=0x7f080000;
        public static int ContentActionBar=0x7f080001;
        public static int SelectPopupDialog=0x7f080002;
    }
}
