#!/usr/bin/env python
#
# Copyright 2014 mogoweb. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""replace R.java with the proper resource id.

In chromium, content/chrome/ui modules have their own resource. When build chromium testshell, the build system
will generate a new R.java filled with the correct ID. If we copy the R.java to chromeview, the resource id is
generated by eclipse plugin, so we should replace with the correct value. 
"""

import StringIO
import string
import re

def replace_r_id(filename):
  file = open(filename)
  output = StringIO.StringIO()
  is_comment_line = False
  classes=[]
  for line in file:
    # skip comment line and blank line
    if string.find(line, "/*") != -1:
      is_comment_line = True
    if line.startswith("//") or not line.split() or is_comment_line:
      output.write(line);
      if string.find(line, "*/") != -1:
        is_comment_line = False
    else: # code line
      # find out class name
      matched = re.search("class\s+\w+\s+", line)
      if matched:
        strlist = matched.group(0).split(' ')
        classes.append(strlist[1])
        print classes
      else:
        matched = re.search("int\s+\w+\s*[=;]", line)
        if matched:
          print matched.group(0)
        # find out the end of class definition and popup
        matched = re.search("}", line)
        if matched:
          classes = classes[0:-1]
  
  #print output.getvalue();

def main():
  replace_r_id("/home/alex/myprojects/chromium_webview_exp/src/chromeview/java/src/org/chromium/content/R.java")

if __name__ == '__main__':
  main()